default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV['DB_USERNAME'] %>
  password: <%= ENV['DB_PASSWORD'] %>
  socket: /var/run/mysqld/mysqld.sock

development:
  <<: *default
  database: CircleCI_first_build_development

test:
  <<: *default
  database: CircleCI_first_build_test

production:
  <<: *default
  database: CircleCI_first_build_production
  username: CircleCI_first_build
  password: <%= ENV['CIRCLECI_FIRST_BUILD_DATABASE_PASSWORD'] %>
